### ISSUE TITLE
Suggestion - Reloading New Creature Entries like items. 

### ISSUE THREAD

**Issue by jrc13245** [azerothcore/mod-betteritemreloading#2]
So this module may have been based off of an older version of this script that only reloaded items.
[(http://www.ac-web.org/forums/showthread.php?233198-Better-Item-Reload-(Includes-full-Item-and-Creature-Template-reloads))](url)
[https://gist.github.com/loud21/1612f69b20e17f5252f9733890bab81b ](url)
In this newer version there is a reload for new entries for creatures. Is this possible?

**Comment by BarbzYHOOL** [comment]
For information, this module is the original work, but the script linked has added a bit more features but it's for TC and not AC hence why a copy paste will not work

**Comment by pangolp** [comment]
Sorry, but I am going to close this issue. If you think I'm wrong, feel free to let me know.
