### ISSUE TITLE
If using the command in console, it will immediately crash

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-betteritemreloading#3]
Type `.breload item 926` in the console and crash

very problematic

solutions:
- fix the crash :D
- or remove the usage in console

**Comment by BarbzYHOOL** [comment]
Just had an idea to solve this, add the SQL for `command` and put max level 3, so it's not usable in console

Not a proper fix but better than none

**Comment by Rochet2** [comment]
Doesnt level 4 have access to level 3 and all levels under it anyways?
FYI the `true` here means that you can call the command from console.
Changing it to false means only ingame players can call it:
https://github.com/azerothcore/mod-better-item-reloading/blob/master/src/BetterItemReloading.cpp#L18-L23

**Comment by BarbzYHOOL** [comment]
yes, i just confused it, ok will try this, it's still a hacky solution, right?

**Comment by Rochet2** [comment]
If the command requires a player then not.
Otherwise it could probably be actually coded to work like you said.

**Comment by BarbzYHOOL** [comment]
Well, in fact if it was fixed in the console, we could reload the item without logging ingame, which is always a small timesave, always good to have

**Comment by BarbzYHOOL** [comment]
if someone can fix the crash, it will be much better though :D

**Comment by Kaev** [comment]
> Well, in fact if it was fixed in the console, we could reload the item without logging ingame, which is always a small timesave, always good to have

I haven't realized that there were created 2 issues on here because i only get mails of my original repo. I'll try to fix that error in the next few days. Thanks for reporting it.
