### ISSUE TITLE
Error compiler

### ISSUE THREAD

**Issue by wowfun335** [azerothcore/mod-betteritemreloading#7]
Hello gentlemen, I encountered an error when compiling an assembly with the addition of the Betteritemreload module
I hope you can help me solve the problem
identifier 'Tokenizer' is not defined
![Screenshot_3](https://user-images.githubusercontent.com/97195498/205940281-87027e2c-954f-4094-98aa-5370f62435ee.jpg)
![image](https://user-images.githubusercontent.com/97195498/205940350-b20c9cd6-c57f-4f41-a41b-610f1ad7f895.png)
![image](https://user-images.githubusercontent.com/97195498/205940401-9e5c11a5-c1c9-49f4-b232-c003dd77ea01.png)
![image](https://user-images.githubusercontent.com/97195498/205940438-d804cd3c-44ef-4983-a894-6ec71369c6db.png)

**Comment by Helias** [comment]
this is related to this https://github.com/azerothcore/azerothcore-wotlk/pull/10121

**Comment by Helias** [comment]
a lot of things must be rewritten here...

**Comment by Helias** [comment]
I partially fixed it here https://github.com/azerothcore/mod-better-item-reloading/pull/8 , but I am blocked for another issue

**Comment by EricksOliveira** [comment]
Any news?

**Comment by pangolp** [comment]
Today I will work on the module almost certainly, and check to update it to the latest version of the emulator.
